AllCops:
  Include:
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
  Exclude:
    - 'vendor/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: false
  StyleGuideCopsOnly: false

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Enabled: true
  Max: 100

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
