AllCops:
  Include:
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
  Exclude:
    - 'vendor/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: false
  StyleGuideCopsOnly: false

Rails:
  Enabled: true

Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
  Max: 15

Naming/AccessorMethodName:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StructInheritance:
  Enabled: false
