version: '3'
volumes:
  db-data:
    external: false
services:
  app:
    build: .
    command: bundle exec rails s
    env_file:
      - ".env"
    ports:
      - 3000:3000
    depends_on:
      - setup
      - db
  setup:
    build: .
    command: bundle exec rails db:setup
    env_file:
      - ".env"
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ".env"
